# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &Lender
        Name: LenderMSP
        ID: LenderMSP
        MSPDir: crypto-config/peerOrganizations/lender.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('LenderMSP.admin', 'LenderMSP.peer', 'LenderMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('LenderMSP.admin', 'LenderMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('LenderMSP.admin')"

    - &Borrower
        Name: BorrowerMSP
        ID: BorrowerMSP
        MSPDir: crypto-config/peerOrganizations/borrower.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('BorrowerMSP.admin', 'BorrowerMSP.peer', 'BorrowerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('BorrowerMSP.admin', 'BorrowerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('BorrowerMSP.admin')"

    - &Broker
        Name: BokerMSP
        ID: BrokerMSP
        MSPDir: crypto-config/peerOrganizations/broker.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('BrokerMSP.admin', 'BrokerMSP.peer', 'BrokerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('BrokerMSP.admin', 'BrokerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('BrokerMSP.admin')"
    
    - &Investor
        Name: InvestorMSP
        ID: InvestorMSP
        MSPDir: crypto-config/peerOrganizations/investor.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('InvestorMSP.admin', 'InvestorMSP.peer', 'InvestorMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('InvestorMSP.admin', 'InvestorMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('InvestorMSP.admin')"

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.example.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    TwoOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Lender
                    - *Borrower
                    - *Broker
                    - *Investor
    TwoOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Lender
                - *Borrower
                - *Broker
                - *Investor
            Capabilities:
                <<: *ApplicationCapabilities

