# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.lender.example.com:
  peer0.borrower.example.com:
  peer0.broker.example.com:
  peer0.investor.example.com:

  caLender:
  caBorrower:
  caBroker:
  caInvestor:

networks:
  network:

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - network

  peer0.lender.example.com:
    container_name: peer0.lender.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.lender.example.com
    networks:
      - network

    peer0.borrower.example.com:
      container_name: peer0.borrower.example.com
      extends:
        file:  base/docker-compose-base.yaml
        service: peer0.borrower.example.com
      networks:
        - network

  peer0.broker.example.com:
      container_name: peer0.broker.example.com
      extends:
        file:  base/docker-compose-base.yaml
        service: peer0.broker.example.com
      networks:
        - network

  peer0.investor.example.com:
      container_name: peer0.investor.example.com
      extends:
        file:  base/docker-compose-base.yaml
        service: peer0.investor.example.com
      networks:
        - network



  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.lender.example.com:7051
      - CORE_PEER_LOCALMSPID=LenderMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/lender.example.com/peers/peer0.lender.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/lender.example.com/peers/peer0.lender.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/lender.example.com/peers/peer0.lender.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/lender.example.com/users/Admin@lender.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.lender.example.com:
      - peer0.borrower.example.com:
      - peer0.broker.example.com:
      - peer0.investor.example.com:
      - caLender:
      - caBorrower:
      - caBroker:
      - caInvestor:
    networks:
      - network
