# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.lender.example.com
      - CORE_PEER_ADDRESS=peer0.lender.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.lender.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.borrower.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.lender.example.com:7051
      - CORE_PEER_LOCALMSPID=LenderMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/lender.example.com/peers/peer0.lender.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/lender.example.com/peers/peer0.lender.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.example.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.borrower.example.com:
    container_name: peer0.borrower.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.borrower.example.com
      - CORE_PEER_ADDRESS=peer0.borrower.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.borrower.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.borrower.example.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.lender.example.com:8051
      - CORE_PEER_LOCALMSPID=BorrowerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/borrower.example.com/peers/peer0.borrower.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/borrower.example.com/peers/peer0.borrower.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.borrower.example.com:/var/hyperledger/production
    ports:
      - 9051:9051


    peer0.broker.example.com:
    container_name: peer0.broker.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.broker.example.com
      - CORE_PEER_ADDRESS=peer0.broker.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.broker.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.broker.example.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.lender.example.com:8051
      - CORE_PEER_LOCALMSPID=BrokerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/broker.example.com/peers/peer0.broker.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/broker.example.com/peers/peer0.broker.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.broker.example.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.investor.example.com:
    container_name: peer0.investor.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.investor.example.com
      - CORE_PEER_ADDRESS=peer0.investor.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.investor.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.investor.example.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.lender.example.com:8051
      - CORE_PEER_LOCALMSPID=InvestorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/investor.example.com/peers/peer0.investor.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/investor.example.com/peers/peer0.investor.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.investor.example.com:/var/hyperledger/production
    ports:
      - 11051:11051

    caLender:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-lender
      - FABRIC_CA_SERVER_CA_NAME=ca-lender
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.lender.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.lender.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/lender.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

  caBorrower:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-borrower
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.borrower.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.borrower.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/borrower.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
 
 caBroker:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-broker
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.broker.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.broker.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/broker.example.com/ca/:/etc/hyperledger/fabric-ca-server-config


  caInvestor:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-investor
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.investor.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "11054:11054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.investor.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/investor.example.com/ca/:/etc/hyperledger/fabric-ca-server-config